/* This file is automatically generated by running `convex dev`. */
/* eslint-disable */

import type { ApiFromModules } from "convex/server"
import type * as cakes from "../cakes"
import type * as categories from "../categories"

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about what functions are available and their
 * types. You'll use this type in your client code to make queries and mutations
 * to the Convex backend.
 */
export type API = ApiFromModules<{
  cakes: typeof cakes
  categories: typeof categories
}>

